---

# Install custom vim
- name: VIM | Clone vim config
  git: repo=https://github.com/staylward/vim-config.git
       dest={{ local_home }}/.vim-config
       update=yes
       accept_hostkey=yes
       recursive=yes

- name: VIM | Created symlink (vimrc)
  file: src={{ local_home }}/.vim-config/vimrc dest={{ local_home }}/.vimrc owner={{ user }} group={{ user }} state=link

- name: VIM | Created symlink (.vim/)
  file: src={{ local_home }}/.vim-config/vim dest={{ local_home }}/.vim owner={{ user }} group={{ user }} state=link

